### ISSUE TITLE
interface for **gradescope** grading

### ISSUE THREAD

**Issue by tbrown122387** [tbrown122387/autograder_gen_site#1]
One part core functionality is that this site must generate an `autograder.zip` file based on the following inputs for any given assignment. This `.zip` file is what the instructor needs to upload to [gradescope](https://www.gradescope.com/). Right now, we just need to write code that accepts all of these inputs. Don’t worry about doing anything with the inputs yet, or with providing output.

Inputs
- [x] Name of the assignment submission expected from students (e.g. `homework1.R`)
- [x] List of extra packages they want to authorize students to use (e.g. `tidyverse`, `MASS`)
- [x] external `.csv` file data sets (variable number)
- [x] variable number of `logical` expressions that the instructor expects to be true (e.g. `myData[1,1] == 6`), along with an associated name of the test, and whether its truth value should be visible to students before the deadline has passed
- [x] (optional) an instructor can provide a `my_tests.R` file with `logical` expressions written

Extra thoughts:
 1. Some of these items imply a "dynamic user interface". For example, we do not know ahead of time how many tests an instructor wants to upload. We need to allow a user to increase the number of tests at will. Same goes for `.csv` uploads.
 2. Let's not worry about what to do with these inputs yet. I will probably get involved with this after the inputs have been defined. 
 3. Let's not worry about downloads or returning the zip file yet, either.

**Comment by tbrown122387** [comment]
first draft of ui ab81ac2 thanks to @tzhai2 
@all-contributors please add @tzhai2 for code

**Comment by tbrown122387** [comment]
Few more comments/questions about the inputs:

1. name of the assignment submission is just a simple string not a file (e.g. `homework1.R`) Maybe use something like `textInput()` instead of `fileInput()`
2. list of extra packages could be a single string, separated by commas, and then we can separate/parse it later
3. external `.csv` file data sets are still file uploads, but there are a varying number of them. How can we add a variable amount of `fileInput`s?
4. Same goes for the `logical` expressions that the instructor expects to be true (e.g. `myData[1,1] == 6`). How do we add a varying number of these? These are text inputs though, n ot file inputs.
5. names and visibility settings are coupled with the above logical expressions. So whenever we add a new logical test window entry, we need to add a corresponding one for the name of ht etest, and corresponding `varSelectInput()` to choose whether it's hidden or visible.
6. (optional) an instructor can provide a `my_tests.R` file with `logical` expressions written. I'm not sure how we should handle this. If the instructor provides a file, we should hide all of the above buttons and text inputs that create the tests. This sounds complicated so maybe we should hold off on this part

**Comment by howardhu99** [comment]
I would say for 3. we can add `multiple = FALSE` in `fileInputs` to allow users to upload multiple csv files at the same time.

**Comment by tbrown122387** [comment]
Let's get rid of the last checkpoint: "(optional) an instructor can provide a my_tests.R file with logical expressions written." 

That leaves only one remaining checkpoint: "external .csv file data sets (variable number)"

@nithvijay  could you elaborate on your TODO: 

```
##  TODO: These functions all create files in the R/ directory, which works locally, 
##  but isn't great long term. I think using temp files or keeping the files in-memory 
##  would help when multiple people are using the website."
```

**Comment by nithvijay** [comment]
Regarding "external .csv file data sets (variable number)". The current implementation does support multiple data sets. It is just unintuitive because the user has to hold control or command when selecting more than one data set. We can instead change this to be more like tests where there is a button to add/remove datasets.

For the TODO: It may not be an issue, but currently the code generates the intermediate files (setup.sh, run_autograder, etc.) and puts them in the directory with the other code. This probably is not the best behavior because if multiple users use the app at the same time, there could be weird issues with overwriting files before one user is done with them. I'm not sure what the ideal solution would be, but in-memory files would ensure that no files are being created on the server itself. Tempfiles that can be deleted as soon as they are not needed would work as well, but I still need to learn how to implement it in R.

**Comment by tbrown122387** [comment]
Didn’t even notice the multiple file uploads. Woops.

regarding second point, maybe just throw an `unlink()` in there. https://community.rstudio.com/t/delete-temp-files-in-shiny/20473 

R has some temp file stuff but it might not be suitable. The `tempfile` function creates files with random names, but our names need to be specific. There’s a tempdir function but cleanup happens when R session terminates.

**Comment by tbrown122387** [comment]
I think the modules broke the `removeTests` button. Haven't quite been able to figure it out yet. Otherwise I think this issue is a wrap
